#!/bin/bash

if [ $# -lt 1 ] ; then
  echo "Usage: new_post title [YYYY-MM-DD]"
  exit 1
fi

if [ $# -eq 4 ] ; then
  timestamp="$2-$3-$4"
else
  timestamp=$(date "+%Y-%m-%d")
fi
posts_dir="_posts"
filename="$posts_dir/$timestamp-$1.md"

echo -e "---\nlayout: post"                  >  $filename
echo -e "title:  \"$1\""                     >> $filename
echo -e "date:   $timestamp 00:00:00 -0700"  >> $filename
echo -e "categories: \n---"                  >> $filename